version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build:
    working_directory: ~/app
    executor:
      name: node/default
    steps:
      - checkout
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run ci
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/app
  deploy:
    working_directory: ~/app
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - setup_remote_docker
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i ~/caches/app.tar | true
      - run:
          name: Build application Docker image
          command: |
            pwd
            docker build -t vuesion .
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p ~/caches
            docker save -o ~/caches/app.tar vuesion
#      - save_cache:
#          key: v1-{{ .Branch }}-{{ epoch }}
#          paths:
#            - /caches/app.tar
      - deploy:
          name: Push application Docker image
          command: |
            docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
            docker tag vuesion "${DOCKER_USER}/vuesion:${CIRCLE_SHA1}"
            docker push "${DOCKER_USER}/vuesion:${CIRCLE_SHA1}"


workflows:
    build-and-test:
      jobs:
        - build
        - deploy:
            requires:
              - build