apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
  name: "showcase"
  labels:
    app: "showcase"
spec:
  type: LoadBalancer
  ports:
    - name: "http"
      port: 80
      targetPort: 3000
  selector:
    app: "showcase"